platform :ios, '13.0'

target 'Recipes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Recipes
  pod 'RealmSwift'
  pod 'SnapKit'
  pod 'IQKeyboardManagerSwift'
  pod 'BSImagePicker'
  
  target 'RecipesTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'RecipesUITests' do
    # Pods for testing
  end
end
